---
title: "Exploratory analysis"
author: "Jakey Lebwohl"
date: "2023-07-12"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Load the weather data

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

```

## `group_by`

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  ungroup(month)
```

## Counting things

counting month / name observations

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs = n())
```

`count`

```{r}
weather_df %>% 
  count(month, name = "n_obs")
```

**NEVER** use base R's `table` function

Other counters

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_days = n_distinct(date)
    )
```
 
```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(cold = case_when(
    tmax < 5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE ~ ""
   )
  ) %>% 
  group_by(name, cold) %>% 
  summarize(count = n()) 

#%>% 
#  pivot_wider(
#    names_from = "cold",
 #   values_from = "count"
 # )
  

```

```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(cold = case_when(
    tmax < 5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE ~ ""
   )
  ) %>% 
  janitor::tabyl(name, cold)
```

## General summaries

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE)
    )
  
```

This is a dataframe!

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE)
    ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

Suppose you want to summarize many columns

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    across(prcp:tmin, mean)
  )
```

Sometimes your results are easier to read in another format

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE   )) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digits = 2)
```

## `group_by` and `mutate`

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
  ) %>%
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```

Window functions

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(temp_rank = min_rank(desc(tmax))) %>% 
  ggplot(aes(x = date, y = temp_rank, color = name)) + 
  geom_point(alpha = .5)
```


Lag

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(temp_change = tmax - lag(tmax)) %>%
  summarize(
    temp_change_max = max(temp_change, na.rm = TRUE),
    temp_change_sd = sd(temp_change, na.rm = TRUE)
  )
```

```{r}
weather_df %>% 
  transform(month = as.factor(month)) %>% 
  group_by(name) %>% 
  mutate(temp_change = tmax - lag(tmax)) %>%
  ggplot(aes(x = date, y = temp_change, color = month)) + 
  geom_point(alpha = 0.9) + 
  scale_color_hue(h = c(0, 360))
```

